spring:
    datasource:
      url: jdbc:mysql://localhost:3306/sample
      username: root
      password: Pankaj39@123
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
